[general]
live_config_reload = true

[terminal]

[cursor]
style = "Block"

[font]
size = 12.0

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[font.normal]
family = "Iosevka Term"
style = "Regular"

[font.offset]
x = 1
y = 1

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/fish"

[window]
opacity = 0.95

[window.dimensions]
columns = 105
lines = 22

[mouse]

[[mouse.bindings]]
action = "Copy"
mouse = "Middle"

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[keyboard]

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Alt"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"
