live_config_reload = true

[window]
dimensions = { columns = 105, lines = 22 }
padding = { x = 10, y = 5 }
opacity = 0.90
blur = true

[shell]
program = "/usr/bin/fish"

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Block"

[font]
size = 12.0
bold =        { family = "Iosevka Term", style = "Bold" }
bold_italic = { family = "Iosevka Term", style = "Bold Italic" }
italic =      { family = "Iosevka Term", style = "Italic" }
normal =      { family = "Iosevka Term", style = "Regular" }
offset =      { x = 1, y = 1 }

[bell]
animation = "EaseOutExpo"
duration  = 0
color     = "#C0C5CE"
command   = { program = "notify-send", args = ["alacritty", "bell",] }

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Middle", action = "Copy" },
  { mouse = "Right",  action = "Paste" },
]

[keyboard]
bindings = [
  { action = "Paste",             mods = "Alt",           key = "V" },
  { action = "Copy",              mods = "Alt",           key = "C" },
  { action = "ClearHistory",      mods = "Alt",           key = "K" },
  { action = "SpawnNewInstance",  mods = "Alt",           key = "N" },
  { action = "Quit",              mods = "Alt",           key = "W" },
  { action = "Quit",              mods = "Alt",           key = "Q" },
  { action = "SearchForward",     mods = "Alt",           key = "F",      mode = "~Search" },
  { action = "SearchBackward",    mods = "Alt",           key = "B",      mode = "~Search" },
  { action = "IncreaseFontSize",  mods = "Control",       key = "Plus" },
  { action = "IncreaseFontSize",  mods = "Control",       key = "NumpadAdd" },
  { action = "DecreaseFontSize",  mods = "Control",       key = "Minus" },
  { action = "DecreaseFontSize",  mods = "Control",       key = "NumpadSubtract" },
  { chars = "\u0003",             mods = "Control|Shift", key = "C" },
]
