live_config_reload: true

selection:
  save_to_clipboard: true

font:
  normal:
    family: Iosevka Term
    style: Regular
  bold:
    family: Iosevka Term
    style: Bold

  italic:
    family: Iosevka Term 
    style: Italic

  bold_italic:
    family: Iosevka Term
    style: Bold Italic

  size: 15.0

  offset:
    x: 1
    y: 1

background_opacity: 0.8

cursor:
  style: Block

shell:
  program: /bin/zsh

launcher:
  program: xdg-open
  args: []

mouse_bindings:
  - { mouse: Middle, action: Copy }
  - { mouse: Right, action: Paste }

key_bindings:
  - { key: V, mods: Alt,        action: Paste             }
  - { key: C, mods: Alt,        action: Copy              }
  - { key: C, mods: Alt|Shift,  chars: "\x03"             }
  - { key: K, mods: Alt,        action: ClearHistory      }
  - { key: N, mods: Alt,        action: SpawnNewInstance  }
  - { key: W, mods: Alt,        action: Quit              }
  - { key: Q, mods: Alt,        action: Quit              }
  - { key: K, mods: Alt,        chars: "\x0c"             }

  - { key: F,              mods: Control, mode: ~Search,    action: SearchForward    }
  - { key: B,              mods: Control, mode: ~Search,    action: SearchBackward   }
  - { key: Plus,           mods: Control,                   action: IncreaseFontSize }
  - { key: NumpadAdd,      mods: Control,                   action: IncreaseFontSize }
  - { key: Minus,          mods: Control,                   action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Control,                   action: DecreaseFontSize }
