#!/bin/sh

# merged and modified luke smith's mount and unmount script and imported to rofi

roficonfig=~/.config/rofi/prompt.rasi
mountpoint=~/mnt/Cell

export SUDO_ASKPASS=~/.config/rofi/mount/askpass  #uncomment this line if you already have askpass setuped, if you're using askpass this way don't use this script in terminal it'll echo your password. use it with shortcuts instead.


androiddevices=$(simple-mtpfs -l 2>/dev/null)
[ -z "$androiddevices" ] && printf "Exit" | rofi -config $roficonfig -dmenu -i -p "No Android Device Found" && exit

chk=$(printf "Mount\nUnmount" | rofi -config $roficonfig -dmenu -i -p "Android Device: ")

case $chk in
	Unmount)
	unmountable=$(grep simple-mtpfs /etc/mtab 2>/dev/null)
	if [ -z "$unmountable" ]; then
	printf "Exit" | rofi -config $roficonfig -dmenu -i -p "Nothing to Unmount" && exit
	else
	devices="$(awk '/simple-mtpfs/ {print $2}' /etc/mtab | rofi -config $roficonfig -dmenu -fuzzy -i -p "Choose Device to Unmount")"
	fusermount -u $devices && printf "exit" | rofi -config $roficonfig -dmenu -i -p "Unmounted Successfully"
	fi

	;;
	Mount)
	device="$(echo "$androiddevices" | rofi -config $roficonfig -dmenu -i -p "Choose Device")"
	simple-mtpfs --device "$device" "$mountpoint" && echo "Exit" | rofi -config $roficonfig -dmenu -i -p "Mounted Successfully" && exit
	echo "Ok" | rofi -config $roficonfig -dmenu -i -p "Tap Allow on your phone, after that Enter."
	simple-mtpfs --device "$device" "$mountpoint" &&  echo "Exit" | rofi -config $roficonfig -dmenu -i -p "Mounted Successfully" || echo "Exit" | rofi -config $roficonfig -dmenu -i -p "not Mounted"
esac 2>/dev/null
